x-airflow-common: &airflow-common
  build: .
  networks:
    - datalab
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    # AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    # AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    TMP_ERROR_MESSAGE_RECEPTION_DOSSIER_ID: ${TMP_ERROR_MESSAGE_RECEPTION_DOSSIER_ID:-}
    TMP_ERROR_MESSAGE_RECEPTION_DEMARCHE_TOKEN: ${TMP_ERROR_MESSAGE_RECEPTION_DEMARCHE_TOKEN:-}

    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}

    # Metrics configuration
    AIRFLOW__METRICS__STATSD_ON: "True"
    AIRFLOW__METRICS__STATSD_HOST: "statsd-exporter"
    AIRFLOW__METRICS__STATSD_PORT: "8125"
    AIRFLOW__METRICS__STATSD_PREFIX: "airflow"

    PYTHONPATH: /opt/airflow
    # yamllint disable rule:line-length
    # Use simple http server on scheduler for health checks
    # See https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/check-health.html#scheduler-health-check-server
    # yamllint enable rule:line-length
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
    # WARNING: Use _PIP_ADDITIONAL_REQUIREMENTS option ONLY for a quick checks
    # for other purpose (development, test and especially production usage) build/extend Airflow image.
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    # _PIP_ADDITIONAL_REQUIREMENTS: ""
  volumes:
    # - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    # - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    # - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    # - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    # - ${AIRFLOW_PROJ_DIR:-.}/utils:/opt/airflow/utils
    # - ${AIRFLOW_PROJ_DIR:-.}/data:/opt/airflow/data
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./include:/opt/airflow/include
    - ./data:/opt/airflow/data
    - ./.env:/opt/airflow/.env
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    - postgres

services:
  # ------------------------------
  # postgres
  # ------------------------------
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./scripts-sql.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - datalab

  # =================================
  # PGADMIN #
  # =================================
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - datalab

  # -----------------------------
  # airflow webserver
  # -----------------------------
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "${AIRFLOW_PORT}:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  # -----------------------------
  # airflow scheduler
  # -----------------------------
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  # ----------------------------
  # airflow init
  # ---------------------------
  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create \
      --username admin \
      --password admin \
      --firstname Admin \
      --lastname User \
      --role Admin \
      --email admin@example.com"

  # -----------------------------
  # Minio
  # ----------------------------
  minio:
    image: minio/minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    volumes:
      - minio-volume:/data
    ports:
      - "9000:9000"
      - "8900:8900"
    command: server --console-address ":8900" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - datalab

  # --------------------------
  # Spark Master
  # --------------------------
  spark-master:
    image: apache/spark:3.5.3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_OPTS="-Dspark.ui.prometheus.enabled=true"
    ports:
      - "8081:8080"
      - "7077:7077"
    networks:
      - datalab

  # --------------------------
  # Spark Worker
  # --------------------------
  spark-worker:
    image: apache/spark:3.5.3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_OPTS="-Dspark.ui.prometheus.enabled=true"
    depends_on:
      - spark-master
    networks:
      - datalab

  # --------------------------
  # Grafana
  # --------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres
      - prometheus
    networks:
      - datalab
    restart: always

  # --------------------------
  # Prometheus
  # --------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - datalab
    restart: always

  # --------------------------
  # StatsD Exporter (Airflow)
  # --------------------------
  statsd-exporter:
    image: prom/statsd-exporter:latest
    container_name: statsd-exporter
    ports:
      - "9102:9102"
      - "8125:8125/udp"
    command: --statsd.listen-udp=:8125 --web.listen-address=:9102
    networks:
      - datalab
    restart: always

  # --------------------------
  # Postgres Exporter
  # --------------------------
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - datalab
    restart: always

  # --------------------------
  # Apache Superset
  # --------------------------
  superset:
    image: apache/superset:3.1.0
    container_name: superset
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_LOAD_EXAMPLES: "no"
      SQLALCHEMY_DATABASE_URI: ${SUPERSET_SQLALCHEMY_DATABASE_URI}
      SUPERSET_SQLALCHEMY_DATABASE_URI: ${SUPERSET_SQLALCHEMY_DATABASE_URI}
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - datalab
    restart: always

  superset-init:
    image: apache/superset:3.1.0
    container_name: superset-init
    depends_on:
      - superset
      - postgres
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SQLALCHEMY_DATABASE_URI: ${SUPERSET_SQLALCHEMY_DATABASE_URI}
    command: >
      bash -c "superset fab create-admin --username ${SUPERSET_ADMIN_USERNAME} --firstname Superset --lastname Admin --email admin@superset.com --password ${SUPERSET_ADMIN_PASSWORD}
      && superset db upgrade
      && superset init"
    networks:
      - datalab

  # --------------------------
  # cAdvisor (Docker Monitoring)
  # --------------------------
  cadvisor:
    # Use standard stable image. Depending on host properties privileged/volumes might warn but works in most WSL/Linux OS.
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - "8082:8080" # Avoid port conflict 8080 with Spark/Airflow and 8081 with Spark-Master
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    networks:
      - datalab
    restart: always

  # --------------------------
  # Loki (Log Aggregation)
  # --------------------------
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - datalab
    restart: always

  # --------------------------
  # Promtail (Log Collector)
  # --------------------------
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/promtail-config.yaml:/etc/promtail/docker-config.yaml:ro
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    networks:
      - datalab
    restart: always

# --------------------------
# Volumes
# --------------------------

volumes:
  postgres-db-volume:
  minio-volume:

networks:
  datalab:
    driver: bridge
